"""Render a Report as standalone Markdown: dated, data gaps up front, every
citation a numbered marker with the full source list at the end.

Used for the archived report.md and served to the UI, so the two never differ.
"""

import re
from datetime import datetime
from urllib.parse import urlparse

from app.graph.state import Citation, Report

_MD_SPECIAL = re.compile(r"([\\`*_\[\]<>#!|])")


def escape(text: str) -> str:
    """Quoted source text (partly third-party web content) is data: render it
    literally, so it can't add links, images, headings or HTML."""
    return _MD_SPECIAL.sub(r"\\\1", text)


def neutralize(text: str) -> str:
    """Model-written prose may echo injected web content. Keep its formatting
    but disarm images, inline links and raw HTML."""
    return text.replace("![", "!\\[").replace("](", "]\\(").replace("<", "\\<")


def _source_line(c: Citation) -> str:
    quote = f'\n   > "{escape(c.quote)}"' if c.quote else ""
    if c.source_type == "news":
        host = escape(urlparse(c.reference).netloc.removeprefix("www.") or c.reference)
        dated = f" ({c.period})" if c.period else ""
        company = f"{c.company} — " if c.company else ""
        url = c.reference.replace("(", "%28").replace(")", "%29").replace(" ", "%20")
        return f"News{dated}: {company}[{host}]({url}){quote}"
    page = f", p.{c.page}" if c.page is not None else ""
    chunk = f", chunk {c.chunk_no}" if c.chunk_no is not None else ""
    return (
        f"{c.company} {c.doc_type} (period {c.period}){page}"
        f" — `{c.source_blob}`{chunk}{quote}"
    )


def render_report_md(
    report: Report,
    *,
    query: str,
    job_id: str,
    generated_at: datetime,
    approved_by: str | None = None,
) -> str:
    numbers: dict[tuple[str, str], int] = {}
    sources: list[Citation] = []

    def marker(c: Citation) -> str:
        key = (c.reference, c.quote)
        if key not in numbers:
            sources.append(c)
            numbers[key] = len(sources)
        return f"[{numbers[key]}]"

    lines = [
        f"# {neutralize(report.subject)}",
        "",
        f"*Question:* {escape(query)}  ",
        f"*Job:* `{job_id}` · *Generated:* {generated_at:%Y-%m-%d %H:%M} UTC"
        + (f" · *Approved by:* {approved_by}" if approved_by else ""),
        "",
    ]
    if report.data_gaps:
        lines += [
            "> **⚠ Data gaps — this report could not use:** "
            + "; ".join(escape(g) for g in report.data_gaps),
            "",
        ]
    lines += ["## Summary", "", neutralize(report.summary), ""]
    for section in report.sections:
        markers = "".join(marker(c) for c in section.citations)
        body = f"{neutralize(section.body)} {markers}".rstrip()
        lines += [f"## {neutralize(section.heading)}", "", body, ""]
    if sources:
        lines += ["## Sources", ""]
        lines += [f"{i}. {_source_line(c)}" for i, c in enumerate(sources, 1)]
        lines.append("")
    lines.append(
        "*Generated by the Azure Market Intelligence Agent from SEC 10-K filings"
        " and news. Check every figure against its cited source.*"
    )
    return "\n".join(lines) + "\n"
